package app.yarmak.newsportal.controller.concrete;

public enum CommandName {
	GO_TO_AUTH, DO_AUTH, NO_AUTH,
	GO_TO_REGISTRATION,DO_REGISTRATION, 
	GO_TO_INDEX_MAIN, 
	GO_TO_PERSONAL_ACCOUNT, 
	GO_TO_APPLY_AUTHOR,DO_APPLY_AUTHOR,GO_TO_APPLICATION_SUBMIT,
	GO_TO_EDIT_NEWS, EDIT_NEWS,
	GO_TO_ALL_NEWS_PAGE, GO_TO_PAGE_NEWS,
	GO_TO_ADD_NEWS_PAGE,ADD_NEWS,
	GO_TO_CATEGORY_PAGE,
	DELETE_NEWS,
	SEARCH_NEWS,
	LOG_OUT,
	NO_SUCH_COMMAND
}
